### ISSUE TITLE
Friendly tracker not present

### ISSUE THREAD

**Issue by OshaIsMe** [batstyx/Graveyard#10]
As title states, I am unable to see the friendly graveyard tracker. Opponent works fine, but none of the friendly trackers are enabled. 

I am using v. 1.9.0 Graveyard and the most recent update of HDT. 

![Screenshot (109)](https://user-images.githubusercontent.com/94841399/142859474-693af934-bd76-4d9e-b9e2-0ca65334e605.png)

**Comment by batstyx** [comment]
If you're comfortable viewing/editing an xml file (in notepad or similar) then you could check the values of the `PlayerTop` and `PlayerLeft` settings in `%appdata%\HearthstoneDeckTracker\Graveyard.xml`[^1] (closing HDT first). 

If the values are negative or higher than your total screen resolution then it could be the friendly tracker has been accidentally dragged off the edge of the screen by the `Unlock Graveyard` code.
```
<Setting>
  <Name>PlayerTop</Name>
  <Value>765</Value>
</Setting>
```
and 
```
<Setting>
  <Name>PlayerLeft</Name>
  <Value>1317</Value>
</Setting>
```
If they look wrong (unlike the values above *obvs*) then delete the whole of each setting as shown above. 
Otherwise  delete `%appdata%\HearthstoneDeckTracker\Graveyard.xml` to restore **all** the plugin default settings.

If you've still no luck then you could check `%appdata%\HearthstoneDeckTracker\Logs\hdt_log.txt` for any Graveyard related errors

You could also try https://github.com/batstyx/Graveyard/releases/tag/v1.9.1.68 which includes some slightly better behaviour around saving the settings (although it won't fix the location of the friendly tracker if it is off the screen).

[^1]: Not the `Graveyard.xml.bak` file. 
If you can see `Graveyard` and `Graveyard.xml` then open `Graveyard` 
If you can see `Graveyard.xml` and `Graveyard.xml.bak` then open `Graveyard.xml`
