### ISSUE TITLE
Multicaster view

### ISSUE THREAD

**Issue by royard** [batstyx/Graveyard#12]
Hi, first of all I really wanted to thank you for this wonderful plugin - made HDT a lot more useful to me.  
I wanted to bring an issues to your attention, though.  If Mad Scientist or Inconspicuous Rider brings in a secret from deathrattle/battlecry, the Multicaster view will count them as casted, which should not be the case.  FYI, spells brought in by Iceblood Tower does not have this issue.

**Comment by batstyx** [comment]
This seems to be an HDT issue where it's reporting the secrets played by these cards as `Played` rather than `Played from Deck` (which is what happens with cards like Iceblood Tower).

**Affected Cards (found so far)**
- Mad Scientist 
- Inconspicuous Rider
- Sword of the Fallen
- Bellringer Sentry
- Phase Stalker

I'm going to take a look at the HDT code to see if there's a simple fix there. Otherwise it's raise an issue there and hope they have the bandwidth to get to it.

**Comment by royard** [comment]
Thank you for the quick response!  It would be great if there is a simple fix...

**Comment by royard** [comment]
Thank you for submitting the fix to HDT!

**Comment by royard** [comment]
Thank you!  Looks like the issues was fixed.
