### ISSUE TITLE
[HELP] Compile program

### ISSUE THREAD

**Issue by Cyberdr3am** [batstyx/Graveyard#24]
Hello and thank you for taking over for this plugin.
I would like to know how I can compile the plugin knowing that the last release dates from 2022 and that there have been modifications in the code.
I tested with vscode but I can't compile it.
THANKS

**Comment by batstyx** [comment]
If you look at the [Releases](https://github.com/batstyx/Graveyard/releases) page, the last release was a couple of weeks ago.

Also the [![Latest Release](https://img.shields.io/github/release-pre/batstyx/Graveyard.svg)](https://github.com/batstyx/Graveyard/releases) widget links to the same thing.

GitHub only shows the latest release that isn't flagged as pre-release on the front page so I should probably change that default as I always forget to switch it off!

I use [VS 2022 Community Edition](https://visualstudio.microsoft.com/vs/community/)  to build it locally rather than VS Code (although I think that is possible with the right extensions).
